name: Deploy Docs

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4.2.2
        with:
          path:
            StarlitLibrary
      
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'StarlitLibrary/docs/requirements.txt'
      
      - name: Install dependencies
        run: pip install -r StarlitLibrary/docs/requirements.txt
      
      - name: Build website with Sphinx
        run: |
          cd StarlitLibrary/docs
          sphinx-build -M html . _build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: StarlitLibrary/docs/_build/html

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pages
        uses: actions/deploy-pages@v4
