name: Deploy Docs

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/buildDocs.yml

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pages
        uses: actions/deploy-pages@v5
